In [2]:
import pandas as pd
df1 = pd.DataFrame({
    "id" : [1,2,3],
    "name" : ["sumit","ravi","kunal"]
})
df2 = pd.DataFrame({
    "id" : [4,5,6],
    "name" : ["rohan","rahul","punit"]
})

In [3]:
pd.concat([df1,df2])

   id   name
0   1  sumit
1   2   ravi
2   3  kunal
0   4  rohan
1   5  rahul
2   6  punit

In [5]:
pd.concat([df1,df2],ignore_index = True)

   id   name
0   1  sumit
1   2   ravi
2   3  kunal
3   4  rohan
4   5  rahul
5   6  punit

In [4]:
pd.concat([df1,df2], axis = 1)

   id   name  id   name
0   1  sumit   4  rohan
1   2   ravi   5  rahul
2   3  kunal   6  punit